name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          submodules: 'true'

      - name: Set up Yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install
        run: |
          yarn

      - name: Check lint
        run: |
          yarn lint

      - name: Build 🔨
        run: |
          yarn ci